### ISSUE TITLE
Add Placeholder text as an option

### ISSUE THREAD

**Issue by Greg-Obleshchuk** [ThomasDev-de/jquery-bsSelectDrop#1]
Hi ,
I have a change to add a parameter for placeholder and a change to add a checked icon to a multi select .  I went to create a new branch but I can't.

Can you give me rights to create branches but not to push to the main branch.  That way I can check my changes in and create a pull request. You can then see if you like my changes.  

cheers
Greg

**Comment by ThomasDev-de** [comment]
Hi @Greg-Obleshchuk,
I have created a branch rule. Please try if it works like this. I don't have so much experience with github yet

greetings

**Comment by Greg-Obleshchuk** [comment]
Awesome thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Greg-Obleshchuk** [comment]
HI , 
Not seeing any new branch or that ability to create a branch..  I saw the invite but when I clicked on it it didn't work 
_Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account._  

I forked the main branch , so I will see about creating a pull request with the code change I have done to date.
